name: Test the Pull request

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        go: ["1.12", "1.13", "1.14"]
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: install python deps
      run: |
        sudo apt-get install -qq python python-pip
        sudo pip install tox nose

    - name: install go deps
      run: go get golang.org/x/tools/cmd/goimports

    - name: copy heketi repo in go src
      run: |
        mkdir -p /home/runner/go/src/github.com/heketi
        cp -r /home/runner/work/heketi/heketi /home/runner/go/src/github.com/heketi

    - name: install glide and run heketi tests
      working-directory: "/home/runner/go"
      env:
        GOPATH: /home/runner/go
      run: |
        export PATH=$PATH:$GOPATH/bin
        curl -L -o /tmp/glide-v0.13.3-linux-amd64.tar.gz https://github.com/Masterminds/glide/releases/download/v0.13.3/glide-v0.13.3-linux-amd64.tar.gz
        tar -xO -f /tmp/glide-v0.13.3-linux-amd64.tar.gz "linux-amd64/glide" > "$GOPATH/bin/glide"
        chmod 0777 "$GOPATH/bin/glide"
        cd /home/runner/go/src/github.com/heketi/heketi
        make all test COVERAGE=true TESTOPTIONS="-vcstdout"
